### ISSUE TITLE
【报错】无法停止，建议加个退出指令

### ISSUE THREAD

**Issue by Agnes4m** [Kaguya233qwq/nonebot_plugin_kfcrazy#1]
到这一步出问题了，然后无论发什么都回复“您输入的序号有误，请重新输入”
![image](https://user-images.githubusercontent.com/70925546/197129904-d03a99cb-aab0-47ba-87b1-cf625db2bda5.png)

**Comment by Kaguya233qwq** [comment]
请问你是使用的最新版本吗

**Comment by Kaguya233qwq** [comment]
如果是最新版本，请在任意阶段直接发送”退出“即可，不用加命令前缀。图中的店铺列表为空，所以输入什么都是错误的。请尽量使用关键字检索店铺，而不是空格

**Comment by Kaguya233qwq** [comment]
> 到这一步出问题了，然后无论发什么都回复“您输入的序号有误，请重新输入” ![image](https://user-images.githubusercontent.com/70925546/197129904-d03a99cb-aab0-47ba-87b1-cf625db2bda5.png)

如果是最新版本，请在任意阶段直接发送”退出“即可，不用加命令前缀。图中的店铺列表为空，所以输入什么都是错误的。请尽量使用关键字检索店铺，而不是空格
