### ISSUE TITLE
搜索鞍山市店铺数据时只能搜索出马鞍山市的结果

### ISSUE THREAD

**Issue by LHT114514** [Kaguya233qwq/nonebot_plugin_kfcrazy#4]
![pic1](https://user-images.githubusercontent.com/121667105/210086167-206e306e-4ace-4903-ba5c-4c3da672d86a.JPG)
感觉可能是把鞍山自动补全成了马鞍山

**Comment by Kaguya233qwq** [comment]
感谢反馈，我会解决它

**Comment by Kaguya233qwq** [comment]
问题已解决，我会在下个版本中修复它，请耐心等待更新
